organization_name: "Food Insecurity Challenge"
image_filename: ""
summary: "This challenge, from the State of California, asks teams to create an actionable picture of food insecurity in communities and build solutions to tackle the issue."
url: "https://cache.codeforamerica.org/events/national-day-2016/challenge-designing-solutions-to-address-food-insecurity-issues-chhs"
