organization_name: "Food Insecurity Challenge"
image_filename: ""
summary: "This challenge, from the State of California, asks teams to create an actionable picture of food insecurity in communities and build solutions to tackle the issue."
url: "https://github.com/code4sac/ndoch-2016/blob/master/FoodInsecurity.md"
