# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: National Day of Civic Hacking Sacramento 2016
email: hello@codeforsacramento.org
description: > # this means to ignore newlines until "baseurl:"
  Let's build something amazing together.
baseurl: "" # the subpath of your site, e.g. /blog
url: http://ndoch.codeforsacramento.org/ # the base hostname & protocol for your site
repo_url: https://github.com/code4sac/ndoch.codeforsacramento.org

# Build settings
markdown: kramdown

# Play nice with US Design Standards without needing to modify them (drop-in).
sass:
  sass_dir: designstandards/assets/_scss

exclude:
  - Gemfile
  - Gemfile.lock
  - CONTRIBUTING.md
  - LICENSE.md
  - README.md
  - index_includes
